machine:
  time:
    disabled: false # Indicates if the time service is disabled for the machine.
      # description: |
    servers:
      - time.cloudflare.com
    bootTimeout: 2m0s # Specifies the timeout when the node time is considered to be in sync unlocking the boot sequence.